categorie_index:
    path:     /
    defaults: { _controller: "CaroGFaimBundle:categorie:index" }
    methods:  GET

categorie_show:
    path:     /{id}/show
    defaults: { _controller: "CaroGFaimBundle:categorie:show" }
    methods:  GET

categorie_new:
    path:     /new
    defaults: { _controller: "CaroGFaimBundle:categorie:new" }
    methods:  [GET, POST]

categorie_edit:
    path:     /{id}/edit
    defaults: { _controller: "CaroGFaimBundle:categorie:edit" }
    methods:  [GET, POST]

categorie_delete:
    path:     /{id}/delete
    defaults: { _controller: "CaroGFaimBundle:categorie:delete" }
    methods:  [GET, DELETE]
