plat_index:
    path:     /
    defaults: { _controller: "CaroGFaimBundle:plat:index" }
    methods:  GET

plat_show:
    path:     /{id}/show
    defaults: { _controller: "CaroGFaimBundle:plat:show" }
    methods:  GET

plat_new:
    path:     /new
    defaults: { _controller: "CaroGFaimBundle:plat:new" }
    methods:  [GET, POST]

plat_edit:
    path:     /{id}/edit
    defaults: { _controller: "CaroGFaimBundle:plat:edit" }
    methods:  [GET, POST]

plat_delete:
    path:     /{id}/delete
    defaults: { _controller: "CaroGFaimBundle:plat:delete" }
    methods:  DELETE
