caro_g_faim_categorie:
    resource: "@CaroGFaimBundle/Resources/config/routing/categorie.yml"
    prefix:   /categorie

caro_g_faim_ingredient:
    resource: "@CaroGFaimBundle/Resources/config/routing/ingredient.yml"
    prefix:   /ingredient

caro_g_faim_personne:
    resource: "@CaroGFaimBundle/Resources/config/routing/personne.yml"
    prefix:   /personne

caro_g_faim_diner:
    resource: "@CaroGFaimBundle/Resources/config/routing/diner.yml"
    prefix:   /diner

caro_g_faim_plat:
    resource: "@CaroGFaimBundle/Resources/config/routing/plat.yml"
    prefix:   /plat

caro_g_faim_type_plat:
    resource: "@CaroGFaimBundle/Resources/config/routing/type_plat.yml"
    prefix:   /type_plat

caro_g_faim_homepage:
    path:     /
    defaults: { _controller: CaroGFaimBundle:Default:index }


